codecov:
  branch: main

coverage:
  precision: 1
  round: down
  range: "70...100"

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 90%
